version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "11:00"
    open-pull-requests-limit: 10
    labels:
      - kind:deps
    groups:
      patch-updates:
        applies-to: version-updates
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "11:00"
    open-pull-requests-limit: 10
    reviewers:
      - Wondertan
      - renaynay
    labels:
      - kind:deps
    ignore:
      - dependency-name: "*otel*"
        update-types: ["version-update:semver-patch"]
    groups:
      patch-updates:
        applies-to: version-updates
      otel:
        patterns:
          - "go.opentelemetry.io/otel*"
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "11:00"
    open-pull-requests-limit: 10
    labels:
      - kind:deps
    groups:
      patch-updates:
        applies-to: version-updates
